### ISSUE TITLE
Evaluations run much slower on the production server

### ISSUE THREAD

**Issue by sfikas** [Transkribus/competitions#107]
Possibly helpful links
* Python multithreading too slow: https://stackoverflow.com/q/3121109/5615276
* The "GIL": https://docs.python.org/3/glossary.html#term-global-interpreter-lock
* Module multiprocessing: https://docs.python.org/3/library/multiprocessing.html#module-multiprocessing

@TobiasGruening

**Comment by sfikas** [comment]
@TobiasGruening (That was just a FYI, I'm not assigning the issue to you :)

**Comment by TobiasGruening** [comment]
Do you see a solution in near future?

Kind regards,
Tobias

**Comment by sfikas** [comment]
@TobiasGruening I think there is some improvement now..can you confirm with a test submission on your competition?

**Comment by TobiasGruening** [comment]
I get a
"You have recently submitted a method. Competition policy is at most one submission per *20 minutes*. Please re-submit at a later time."
though I didn'T submitted anything. I'll wait half an hour and test again!

**Comment by TobiasGruening** [comment]
Incredibly fast!
Perfect! Thanks.
Close if you want :)

**Comment by sfikas** [comment]
I think there is some problem with the submissions time limit, unrelated (?) to this issue. It happened to me too.
I'll open it to a new issue.
