### ISSUE TITLE
"Private data" - cannot handle ".zip" files

### ISSUE THREAD

**Issue by nikosstam** [Transkribus/competitions#34]

**Comment by sfikas** [comment]
"It's not a bug. It's a feature"

**Comment by sfikas** [comment]
This is already documented:

https://github.com/Transkribus/competitions#7-create-one-or-more-subtrack-models

"""
Private data: Upload data that are not meant to be downloaded by the competition participants.

**This should normally be a compressed tarball. This tarball is automatically decompressed on the server side after the upload completes.**

The private data field is meant to be used as an argument to your evaluation benchmarks. In KWS for example, the private data is a file that contains the information about which query matches with which word.
"""

So if your data is formatted as a zip file, the solution would simply be to convert the zip into a tar.gz or tgz.
