### ISSUE TITLE
Show competition organizers in a certain order

### ISSUE THREAD

**Issue by bgatos** [Transkribus/competitions#41]

**Comment by mauvilsa** [comment]
I would also suggest that the organizers only be shown on the competition home, not on every page of the competition like it is now.

**Comment by sfikas** [comment]
This could be done by having the organizers - competitions relation correspond to some integer value (somehow)
So the higher this value, the higher the organizer appears on the list.

**Comment by sfikas** [comment]
As a halfmeasure, an alphabetical order could be used for the organizers list.

**Comment by sfikas** [comment]
Added two new model fields on 'competitions', as M2M relations between competitions - individuals

Leading_organizers show up higher than midtier_organizers and other organizers.
Midtier_organizers show up higher than other (non-leading) organizers.
