### ISSUE TITLE
Integrate with Baseline metric tool

### ISSUE THREAD

**Issue by sfikas** [Transkribus/competitions#6]
Integrate with baseline metric tool, using it as an evaluator metric.
Related repository at https://github.com/Transkribus/TranskribusBaseLineMetricTool

**Comment by sfikas** [comment]
@TobiasGruening @gundramleifert

**Comment by gundramleifert** [comment]
@sfikas I cannot find the Link to the competition-server - could you make it available via link in read-wiki? Thanks

**Comment by sfikas** [comment]
@gundramleifert I added the url here: https://read02.uibk.ac.at/wiki/index.php/Competitions
