### ISSUE TITLE
Error in tests of TranskribusErrorRates

### ISSUE THREAD

**Issue by gundramleifert** [Transkribus/competitions#61]
related to 3ea83300553330a40858519489c848263c9fd4b7 and the test there is a "file not found" in https://travis-ci.org/Transkribus/competitions/jobs/168631115 . How can we solve that? The file is in scriptnet/competitions/executables/TranskribusErrorRate/testresources/gt.tgz

**Comment by sfikas** [comment]
I noticed! Ill fix this a bit later.. 
Thanks!
