### ISSUE TITLE
limit number of submissions

### ISSUE THREAD

**Issue by sfiel** [Transkribus/competitions#91]
Setting to limit the number of submission (one per day, two per week, ...)
If the results are reported back to the users, the number of submissions should be limited

**Comment by sfikas** [comment]
The mechanism is already in place, since #32 .
The question was what the limit should be. The concensus is that this should change to one submission per hour -- of course this could change in the future.

**Comment by sfiel** [comment]
Thank you for the clarification
The problem with1 submission per hour is, that the performance of the algorithm should be hidden, otherwise the platform will be used for parameter evaluation, which is not the point

**Comment by sfikas** [comment]
What is to be implemented now is that submissions' results will be visible only to the submitter (#90).
Are you suggesting a more strict limit? Like one submission per day?

**Comment by sfiel** [comment]
In my opinion if there is a limit of 1 submission / hour even the submitter should not be able to see his results. Otherwise I would submit my method every hour with a different parameter set. If the submitter can see his results should be decided by the competition organizers, also the limit of the submission. I think these settings can/should be different for every competition
