### ISSUE TITLE
Consider allowing only zipped submissions and under a certain file size

### ISSUE THREAD

**Issue by sfikas** [Transkribus/competitions#96]
@sfiel @bgatos

**Comment by sfiel** [comment]
Hi,
can you automatically check if the solution is zipped or not? And either give the evaluator function the unpacked or the original file? Because then we don't have to care about this in the evaluator function and you catch errors easier.

Cheers

**Comment by sfikas** [comment]
I think it's better to leave this up to each evaluator function. Not only because it's easier for me :) But consider this scenario : Suppose that submission files are too large uncompressed, and much much small when compressed (which can be the case with, say, XML files). Then maybe best thing to do is *never* uncompress the file, but rather receive it and store it compressed, and access the contents through the corresponding python function, i.e. without ever decompressing them. This can be done with gzip.open, for example (see also http://stackoverflow.com/q/10566558/5615276).

and btw sorry for the really belated answer :)
